<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="GENIUS" name="Test" tests="8" failures="3" timestamp="23 Jul 2017 07:49:27 GMT" time="74.091" errors="0">
  <testcase name="loginLogOut" time="4.197" classname="testcases.TC001_Loginnegative"/>
  <testcase name="loginLogOut" time="6.376" classname="testcases.TC001_LoginLogOut"/>
  <testcase name="createLead" time="7.353" classname="testcases.TC003_CreateLead">
    <failure type="java.lang.RuntimeException" message="FAILED">
      <![CDATA[java.lang.RuntimeException: FAILED
	at utils.Reporter.reportStep(Reporter.java:33)
	at utils.Reporter.reportStep(Reporter.java:43)
	at pages.MyHomePage.<init>(MyHomePage.java:17)
	at pages.HomePage.clickCRMSFA(HomePage.java:27)
	at testcases.TC003_CreateLead.createLead(TC003_CreateLead.java:28)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- createLead -->
  <testcase name="loginLogOut" time="4.585" classname="testcases.TC001_Loginnegative"/>
  <testcase name="loginLogOut" time="7.402" classname="testcases.TC001_LoginLogOut"/>
  <testcase name="loginLogOut" time="3.769" classname="testcases.TC001_Loginnegative"/>
  <testcase name="loginLogOut" time="3.873" classname="testcases.TC001_Loginnegative">
    <failure type="java.lang.RuntimeException" message="FAILED">
      <![CDATA[java.lang.RuntimeException: FAILED
	at utils.Reporter.reportStep(Reporter.java:33)
	at utils.Reporter.reportStep(Reporter.java:43)
	at wrappers.GenericWrappers.verifyTextContainsById(GenericWrappers.java:283)
	at pages.LoginPage.verifyLoginDetails(LoginPage.java:45)
	at testcases.TC001_Loginnegative.loginLogOut(TC001_Loginnegative.java:27)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- loginLogOut -->
  <testcase name="createLead" time="46.612" classname="testcases.TC003_CreateLead">
    <failure type="java.lang.RuntimeException" message="FAILED">
      <![CDATA[java.lang.RuntimeException: FAILED
	at utils.Reporter.reportStep(Reporter.java:33)
	at utils.Reporter.reportStep(Reporter.java:43)
	at wrappers.GenericWrappers.enterById(GenericWrappers.java:139)
	at pages.CreateLeadPage.enterCompanyName(CreateLeadPage.java:23)
	at testcases.TC003_CreateLead.createLead(TC003_CreateLead.java:31)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- createLead -->
</testsuite> <!-- Test -->
