<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="GENIUS" name="testcases.TC001_Loginnegative" tests="1" failures="0" timestamp="10 May 2018 19:33:08 GMT" time="0.128" errors="1">
  <testcase name="loginLogOut" time="0.128" classname="testcases.TC001_Loginnegative">
    <error type="org.testng.TestNGException" message="
The data provider is trying to pass 4 parameters but the method testcases.TC001_Loginnegative#loginLogOut takes 3">
      <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 4 parameters but the method testcases.TC001_Loginnegative#loginLogOut takes 3
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1223)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1118)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
    </error>
  </testcase> <!-- loginLogOut -->
</testsuite> <!-- testcases.TC001_Loginnegative -->
